name: Copy llama

on: [workflow_dispatch]

jobs:
  copy-llama:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy from glitch-llama
      run: |
        ./copy.ps1
        git config --global user.name "Glorp"
        git config --global user.email "glorp@users.noreply.github.com"
        git add -A
        git commit -m "copied some stuff over"
        git push
